// Educational Context and Discipline Mappings
export const DISCIPLINE_MAPPING: Record<string, string> = {
  "Keine Vorgabe": "",
  "Allgemein": "http://w3id.org/openeduhub/vocabs/discipline/720",
  "Alt-Griechisch": "http://w3id.org/openeduhub/vocabs/discipline/20003",
  "Agrarwirtschaft": "http://w3id.org/openeduhub/vocabs/discipline/04001",
  "Arbeit, Ernährung, Soziales": "http://w3id.org/openeduhub/vocabs/discipline/oeh01",
  "Arbeitslehre": "http://w3id.org/openeduhub/vocabs/discipline/020",
  "Arbeitssicherheit": "http://w3id.org/openeduhub/vocabs/discipline/04014",
  "Astronomie": "http://w3id.org/openeduhub/vocabs/discipline/46014",
  "Bautechnik": "http://w3id.org/openeduhub/vocabs/discipline/04002",
  "Berufliche Bildung": "http://w3id.org/openeduhub/vocabs/discipline/040",
  "Biologie": "http://w3id.org/openeduhub/vocabs/discipline/080",
  "Chemie": "http://w3id.org/openeduhub/vocabs/discipline/100",
  "Chinesisch": "http://w3id.org/openeduhub/vocabs/discipline/20041",
  "Darstellendes Spiel": "http://w3id.org/openeduhub/vocabs/discipline/12002",
  "Deutsch": "http://w3id.org/openeduhub/vocabs/discipline/120",
  "Deutsch als Zweitsprache": "http://w3id.org/openeduhub/vocabs/discipline/28002",
  "Elektrotechnik": "http://w3id.org/openeduhub/vocabs/discipline/04005",
  "Ernährung und Hauswirtschaft": "http://w3id.org/openeduhub/vocabs/discipline/04006",
  "Englisch": "http://w3id.org/openeduhub/vocabs/discipline/20001",
  "Pädagogik": "http://w3id.org/openeduhub/vocabs/discipline/440",
  "Esperanto": "http://w3id.org/openeduhub/vocabs/discipline/20090",
  "Ethik": "http://w3id.org/openeduhub/vocabs/discipline/160",
  "Farbtechnik und Raumgestaltung": "http://w3id.org/openeduhub/vocabs/discipline/04007",
  "Französisch": "http://w3id.org/openeduhub/vocabs/discipline/20002",
  "Geografie": "http://w3id.org/openeduhub/vocabs/discipline/220",
  "Geschichte": "http://w3id.org/openeduhub/vocabs/discipline/240",
  "Gesellschaftskunde": "http://w3id.org/openeduhub/vocabs/discipline/48005",
  "Gesundheit": "http://w3id.org/openeduhub/vocabs/discipline/260",
  "Hauswirtschaft": "http://w3id.org/openeduhub/vocabs/discipline/50001",
  "Holztechnik": "http://w3id.org/openeduhub/vocabs/discipline/04009",
  "Informatik": "http://w3id.org/openeduhub/vocabs/discipline/320",
  "Interkulturelle Bildung": "http://w3id.org/openeduhub/vocabs/discipline/340",
  "Italienisch": "http://w3id.org/openeduhub/vocabs/discipline/20004",
  "Kunst": "http://w3id.org/openeduhub/vocabs/discipline/060",
  "Körperpflege": "http://w3id.org/openeduhub/vocabs/discipline/04010",
  "Latein": "http://w3id.org/openeduhub/vocabs/discipline/20005",
  "Mathematik": "http://w3id.org/openeduhub/vocabs/discipline/380",
  "Mechatronik": "http://w3id.org/openeduhub/vocabs/discipline/oeh04010",
  "Medienbildung": "http://w3id.org/openeduhub/vocabs/discipline/900",
  "Mediendidaktik": "http://w3id.org/openeduhub/vocabs/discipline/400",
  "Metalltechnik": "http://w3id.org/openeduhub/vocabs/discipline/04011",
  "MINT": "http://w3id.org/openeduhub/vocabs/discipline/04003",
  "Musik": "http://w3id.org/openeduhub/vocabs/discipline/420",
  "Nachhaltigkeit": "http://w3id.org/openeduhub/vocabs/discipline/64018",
  "Niederdeutsch": "http://w3id.org/openeduhub/vocabs/discipline/niederdeutsch",
  "Open Educational Resources": "http://w3id.org/openeduhub/vocabs/discipline/44099",
  "Philosophie": "http://w3id.org/openeduhub/vocabs/discipline/450",
  "Physik": "http://w3id.org/openeduhub/vocabs/discipline/460",
  "Politik": "http://w3id.org/openeduhub/vocabs/discipline/480",
  "Psychologie": "http://w3id.org/openeduhub/vocabs/discipline/510",
  "Religion": "http://w3id.org/openeduhub/vocabs/discipline/520",
  "Russisch": "http://w3id.org/openeduhub/vocabs/discipline/20006",
  "Sachunterricht": "http://w3id.org/openeduhub/vocabs/discipline/28010",
  "Sexualerziehung": "http://w3id.org/openeduhub/vocabs/discipline/560",
  "Sonderpädagogik": "http://w3id.org/openeduhub/vocabs/discipline/44006",
  "Sorbisch": "http://w3id.org/openeduhub/vocabs/discipline/20009",
  "Sozialpädagogik": "http://w3id.org/openeduhub/vocabs/discipline/44007",
  "Spanisch": "http://w3id.org/openeduhub/vocabs/discipline/20007",
  "Sport": "http://w3id.org/openeduhub/vocabs/discipline/600",
  "Textiltechnik und Bekleidung": "http://w3id.org/openeduhub/vocabs/discipline/04012",
  "Türkisch": "http://w3id.org/openeduhub/vocabs/discipline/20008",
  "Wirtschaft und Verwaltung": "http://w3id.org/openeduhub/vocabs/discipline/04013",
  "Wirtschaftskunde": "http://w3id.org/openeduhub/vocabs/discipline/700",
  "Umweltgefährdung, Umweltschutz": "http://w3id.org/openeduhub/vocabs/discipline/640",
  "Verkehrserziehung": "http://w3id.org/openeduhub/vocabs/discipline/660",
  "Weiterbildung": "http://w3id.org/openeduhub/vocabs/discipline/680",
  "Werken": "http://w3id.org/openeduhub/vocabs/discipline/50005",
  "Zeitgemäße Bildung": "http://w3id.org/openeduhub/vocabs/discipline/72001",
  "Sonstiges": "http://w3id.org/openeduhub/vocabs/discipline/999"
};

export const EDUCATIONAL_CONTEXT_MAPPING: Record<string, string> = {
  "Keine Vorgabe": "",
  "Elementarbereich": "http://w3id.org/openeduhub/vocabs/educationalContext/elementarbereich",
  "Primarstufe": "http://w3id.org/openeduhub/vocabs/educationalContext/grundschule",
  "Sekundarstufe I": "http://w3id.org/openeduhub/vocabs/educationalContext/sekundarstufe_1",
  "Sekundarstufe II": "http://w3id.org/openeduhub/vocabs/educationalContext/sekundarstufe_2",
  "Hochschule": "http://w3id.org/openeduhub/vocabs/educationalContext/hochschule",
  "Berufliche Bildung": "http://w3id.org/openeduhub/vocabs/educationalContext/berufliche_bildung",
  "Fortbildung": "http://w3id.org/openeduhub/vocabs/educationalContext/fortbildung",
  "Erwachsenenbildung": "http://w3id.org/openeduhub/vocabs/educationalContext/erwachsenenbildung",
  "Förderschule": "http://w3id.org/openeduhub/vocabs/educationalContext/foerderschule",
  "Fernunterricht": "http://w3id.org/openeduhub/vocabs/educationalContext/fernunterricht"
};

export const EDUCATION_SECTOR_MAPPING: Record<string, string> = {
  "Keine Vorgabe": "",
  "Frühkindlich": "early_childhood",
  "Allgemeinbildend": "general",
  "Berufsbildend": "vocational",
  "Akademisch": "academic"
};